### ISSUE TITLE
Package.json missing

### ISSUE THREAD

**Issue by ketan12sharma** [saurabh3896/grafana-table-filter-search#1]
Hey @saurabh3896, I am trying to build your plugin from source, but in order to do that I need the package.json file to build node dependencies, Seems like the file is missing in this repo.

**Comment by saurabh3896** [comment]
Hi @ketan12sharma , I have updated the repository. You should be able to run it by cloning it into `data/plugins` folder of your grafana source. The code is raw and may have some bugs. Please create a new issue in case you find any bug in code / building parameters. I don't have much experience with Gruntfiles and stuff.
