### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by amjad** [saurabh3896/grafana-table-filter-search#2]
I copied the folder to /var/lib/grafana/plugins. How does this work? I do not see a search bar on my table panel. 

I am using Grafana 5.4.3 on Ubuntu 18.04.

**Comment by saurabh3896** [comment]
I have updated the README.md. Please have a look and let me know if you still encounter an issue. Also, try copying only the `dist` folder to your `plugin` folder if it still doesn't work. @amjad It should even work if you simply clone this repository inside your `var/lib/plugins` folder.

**Comment by amjad** [comment]
@saurabh3896 didnt seem to work. I copied the dist folder in `/var/lib/grafana/plugins` and still the table panel does not have search filter. Do I need to restart or reload the server? Also can you post a screenshot of what this looks like?

**Comment by saurabh3896** [comment]
@amjad Yes, you should try restarting the server. Here is the screenshot : 
![selection_008](https://user-images.githubusercontent.com/13899504/53329381-4f686a80-392f-11e9-976f-31269556b2ce.png)
Note that it doesn't modify the existing table, but is a separate entity/plugin, named `Worksap-table`.
